#ifndef __TYPES_H__
#define __TYPES_H__

typedef enum {SEM_STABLE, SEM_COMPLETE, SEM_GROUNDED, SEM_PREFERRED, SEM_SEMISTABLE, SEM_UNDEFINED} SemanticName;

typedef enum {TASK_ONE_EXT, TASK_ALL_EXTS, TASK_SKEP_INF, TASK_CRED_INF, TASK_UNDEFINED} TaskType;

#endif
