#ifndef __TYPES_H__
#define __TYPES_H__


namespace CoQuiAAS {

typedef enum {SEM_STABLE, SEM_COMPLETE, SEM_GROUNDED, SEM_PREFERRED, SEM_SEMISTABLE, SEM_STAGE, SEM_IDEAL, SEM_TRIATHLON, SEM_UNDEFINED} SemanticName;

typedef enum {TASK_ONE_EXT, TASK_ALL_EXTS, TASK_SKEP_INF, TASK_CRED_INF, TASK_TRIATHLON, TASK_UNDEFINED} TaskType;

}

#endif
